<?php
// Lang
$lang = array(
	"time" => array(
		"s" => "Sekunden",
		"S" => "Sekunde",
		"m" => "Minuten",
		"M" => "Minute",
		"h" => "Stunden",
		"H" => "Stunde",
		"a" => "vor",
		"af" => "ein paar",
		"format" => "%ago %value %time",
		"tformat" => "d.m.y H:i"
	),
	"misc" => array(
		"ok" => "&radic;",
		"fillout" => "Bitte f&uuml;lle alle Felder aus",
		"coin" => "Coin",
		"charname" => "Charakter",
		"coins" => "Coins",
		"noacc" => "Kein Account mit diesem Usernamen oder Passwort gefunden ",
		"pass" => "Passwort",
		"oldpass" => "Altes Passwort",
		"repeat" => "Wiederholen",
		"user" => "Username",
		"level" => "Level",
		"email" => "Email",
		"code" => "L&ouml;schcode",
		"login" => "Login",
		"logout" => "Logout",
		"register" => "Registrieren",
		"forgot" => "Passwort vergessen",
		"accsupport" => "Probleme beim Einloggen?",
		"hello" => "Hallo <b>%username</b>,",
		"youcoin" => "Du hast <b>%coins</b> %coinname!",
		"donate" => "Spenden",
		"char" => "Deine Charaktere",
		"itemshop" => "Itemshop",
		"settings" => "Einstellungen",
		"ranking" => "Rangliste",
		"submit" => "Absenden",
		"allclasses" => "Gesammt",
		"warrior" => "Krieger",
		"assassin" => "Ninja",
		"sura" => "Sura",
		"shaman" => "Schamanen",
		"classrank" => "Klassen-#",
		"class" => "Klasse",
		"search" => "Suchen",
		"download" => "Download",
		"systemrequirements" => "Systemvoraussetzungen",
	),
	"reg" => array(
		"captcha_error" => "Den Captcha, den du eingegeben hast, stimmt nicht.",
		"register_closed" => "Die Registration ist im Moment leider geschlossen.<br/>Bitte versuche es sp&auml;ter nocheinmal, da dies h&ouml;chstwahrscheinlich nur eine tempor&auml;re Ma&szlig;nahme ist.",
		"register_loggedin" => 'Du hast schon einen Account!<br/>Wenn das nicht dein Account ist logge dich bitte aus: <a href="'.$urlmap["logout"].'">Logout</a>',
		"passrepeat_error" => "Das Passwort und die Wiederholung stimmen nicht &uuml;berein.",
		"account_exists" => "Ein Account mit diesem Namen existiert bereits.",
		"codelen_error" => "Dein L&ouml;schcode muss 7 Zeichen lang sein.",
		"email_error" => "Deine Email scheint nicht richtig zu sein",
		"multiacc_error" => "Du hast bereits einen Account auf dieser Email",
		"userminlen_error" => "Dein Username muss mindestens %len Zeichen lang sein",
		"usermaxlen_error" => "Dein Username darf maximal %len Zeichen lang sein",
		"passminlen_error" => "Dein Passwort muss mindestens %len Zeichen lang sein",
		"passmaxlen_error" => "Dein Passwort darf maximal %len Zeichen lang sein",
		"emailsubject" => "Deine Registration auf ".$config["settings"]["name"],
		"emailbody" => "Hallo %username,\nUm deine Registrierung auf ".$config["settings"]["name"]." zu vervollständigen, musst du nur auf diesen Link klicken:\n".$config["settings"]["baseurl"].$urlmap["register"]."&key=%key\n\nDein ".$config["settings"]["name"]." Team",
		"success_emailverify" => "Deine Registration war erfolgreich!<br/>Wir haben dir eine Email geschickt um deine Email Adresse zu bestätigen<br/>Bitte klicke den Link in der Email um deinen Account zu bestätigen",
		"success" => "Deine Registration war erfolgreich!",
		"verify_error" => "Verzifizierung fehlgeschlagen!<br/>Bitte kopiere den Link wenn du Probleme hast!",
		"verify_success" => "Du hast deinen Account erfolgreich verifiziert!<br/>Du kannst nun mit ihm spielen!",
	),
	"sysreq" => array(
		"os" => "OS",
		"cpu" => "CPU",
		"mem" => "RAM",
		"hdd" => "HDD",
		"graphics" => "Grafikkarte",
		"sound" => "Soundkarte",
	),
	"settings" => array(
		"change_password" => "Passwort &auml;ndern",
		"change_password_text" => "Hier kannst du dein Passwort &auml;ndern.<br/>Du musst nur dein altes Passwort eingeben, um zu best&auml;tigen, dass dies dein Account ist.<br/>",
		"change_code" => "L&ouml;schcode &auml;ndern",
		"change_code_text" => "Hier kannst du deinen L&ouml;schcode &auml;ndern<br/>Du musst nur dein Passwort eingeben, um zu best&auml;tigen, dass dies dein Account ist<br/>",
		"reset_safebox" => "Lagerpasswort zur&uuml;cksetzen",
		"reset_safebox_text" => "Hier kannst du dein Lagerpasswort zur&uuml;cksetzen<br/>Falls du dies tust, wird es zu <b>0000000</b> geändert<br/>Du musst nur dein Passwort eingeben, um zu best&auml;tigen, dass dies dein Account ist<br/>",
		"change_email" => "Email &auml;ndern",
		"change_email_text" => "hier kannst du deine aktuelle Email &auml;ndern<br/>Du musst nur dein Passwort eingeben, um zu best&auml;tigen, dass dies dein Account ist<br/>",
		"pass_error" => "Das Passwort stimmt nicht überein!",
		"pass_changed" => "Dein Passwort wurde erfolgreich ge&auml;ndert!",
		"code_changed" => "Dein L&ouml;schcode wurde erfolgreich ge&auml;ndert!",
		"safebox_reseted" => "Dein Lagerpasswort wurde erfolgreich zur&uuml;ckgesetzt! (Es ist jetzt <b>0000000</b>)",
	)
);

?>