<?php
// Lang
$lang = array(
	"time" => array(
		"s" => "seconds",
		"S" => "second",
		"m" => "minutes",
		"M" => "minute",
		"h" => "hours",
		"H" => "hour",
		"a" => "ago",
		"af" => "a few",
		"format" => "%value %time %ago",
		"tformat" => "d.m.y H:i"
	),
	"misc" => array(
		"fillout" => "Please fill out all fields",
		"coin" => "Coin",
		"coins" => "Coins",
		"noacc" => "No account with that password or username found",
		"pass" => "Password",
		"repeat" => "Repeat",
		"user" => "Username",
		"email" => "Email",
		"code" => "Code",
		"login" => "Login",
		"logout" => "Logout",
		"register" => "Register",
		"forgot" => "Forgot password",
		"accsupport" => "Trouble signing in?",
		"hello" => "Hello <b>%username</b>,",
		"youcoin" => "You have <b>%coins</b> %coinname!",
		"donate" => "Donate",
		"char" => "Your characters",
		"itemshop" => "Itemshop",
		"settings" => "Settings",
		"submit" => "Submit",
		"banned" => "Your account is banned",
	),
	"reg" => array(
		"captcha_error" => "The captcha you entered is wrong.",
		"register_closed" => "The registration is currently closed<br/>Please check back later cause this is probably just temporary.",
		"register_loggedin" => 'You already have an account.<br/>If this is not your account please <a href="'.$urlmap["logout"].'">Logout</a>',
		"passrepeat_error" => "The password and the repeated one didn't match.",
		"account_exists" => "An account with this name already exists",
		"codelen_error" => "Your code has to be 7 characters long",
		"email_error" => "Your email doesnt seem to be valid",
		"multiacc_error" => "There is already an account on this email",
		"userminlen_error" => "Your username has to be at least %len characters long",
		"usermaxlen_error" => "Your username must be under %len characters long",
		"passminlen_error" => "Your password has to be at least %len characters long",
		"passmaxlen_error" => "Your password must be under %len characters long",
		"emailsubject" => "Your registration on ".$config["settings"]["name"],
		"emailbody" => "Hello %username,\nTo complete your registration on ".$config["settings"]["name"]." you just have to click this link:\n".$config["settings"]["baseurl"].$urlmap["register"]."&key=%key\nYour ".$config["settings"]["name"]." Team",
		"success_emailverify" => "Your Registration was sucessfull!<br/>An email was sent to verify your email adress is valid.<br/>Please click the link in the email to verify your account.",
		"success" => "Your Registration was sucessfull!",
	),
);

?>