<?php
/*
 * This belongs to iMers iMt2-HP-Script
 * https://github.com/imermcmaps/iMt2-HP-Script
 * iMer.cc 2012
 * 
 * Temporary language file for cleaning up/renaming stuff
 */
array(
	"de" => array(
		// General stuff
		"fillout" => "Bitte f&uuml;lle alle Felder aus",
		"needlogin" => "Bitte logge dich ein.",
		"youcoin" => "Du hast <b><span class='coins'>%coins</span></b> %coinname!",
		"coin" => "Coin",
		"coins" => "Coins",
		"online" => "online",
		"offline" => "offline",
		"warrior" => "Krieger",
		"assassin" => "Ninja",
		"sura" => "Sura",
		"shaman" => "Schamanen",
		"back" => "Zur&uuml;ck",
		"next" => "N&auml;chste",
		"charname" => "Name",
		"class" => "Klasse",
		"level" => "Level",
		"ok"=>"&radic;",
		"logout"=>"Logout",
		"login"=>"Login",
		// Time class
		"time_s" => "Sekunden",
		"time_S" => "Sekunde",
		"time_m" => "Minuten",
		"time_M" => "Minute",
		"time_h" => "Stunden",
		"time_H" => "Stunde",
		"time_D" => "Tag",
		"time_d" => "Tagen",
		"time_a" => "vor",
		"time_in" => "in",
		"time_at" => "um",
		"time_now" => "Gerade jetzt",
		"time_af" => "ein paar",
		"time_ystrd" => "Gestern",
		"time_tmrw" => "Morgen",
		"time_format" => "%ago %value %time %at",
		"time_fformat" => "%ago %value %time %at",
		"time_dformat" => "d.m.y H:i",
		// Donate_psc
		"donate" => "Spenden",
		"psc_code_name" => "Code",
		"psc_donate_success" => "Deine Paysafecard ist g&uuml;ltig und wurde erfolgreich eingetragen!<br/> Warte nun, bis ein Teamler deine Paysafecard erneut kontrolliert und dir deine Coins gutschreibt!<br/>Dies sollte <b>maximal 24 Stunden</b> dauern.",
	    "psc_error_fields_blank" => "Sie haben nicht alle Felder ausgef&uuml;llt.",
	    "psc_error_code" => "Bei deinem PIN-Code und/oder Passwort ist ein Fehler aufgetreten. Bitte &uuml;berpr&uuml;fe die korrekte Eingabe des PIN-Code oder Passwort.",
	    "psc_error_code_pw" => "Bei deinem PIN-Code und/oder Passwort ist ein Fehler aufgetreten. Bitte &uuml;berpr&uuml;fe die korrekte Eingabe des PIN-Code oder Passwort.",
	    "psc_error_captcha" => "Der eingegebene Text stimmt nicht mit dem angezeigten &Uuml;berein.",
	    "psc_error_unknown" => "Es ist ein unbekannter Fehler aufgetreten",
	    "psc_error_online" => "Es ist ein unbekannter Fehler aufgetreten. Bitte versuche es sp&auml;ter nocheinmal.",
	    "psc_error_currency" => "Die Paysafecard hat eine nicht akzeptierte W&auml;hrung",
	    "psc_error_empty" => "Die Paysafecard hat ein zu geringes Guthaben.",
	    "psc_error_try" => "Zu viele Fehlversuche",   
		// Itemshop
		"itemshop" => "Itemshop",
		"itemshop_404" => "Ich konnte die Seite die du angefragt hast nicht finden.",
		"itemshop_price" => "Preis",
		"itemshop_buy" => "Kaufen",
		"itemshop_buy_again" => "Nochmal",
		"itemshop_itemerror" => "Ich konnte dieses Item leider nicht finden!",
		"itemshop_priceerror" => "Du hast nicht genug Coins um das zu kaufen!",
		"itemshop_success" => "Das Item wurde erfolgreich gekauft!",
		// Ranking
		"ranking" => "Rangliste",
		"ranking_search_placeholder"=>"Charaktername",
		"ranking_search" => "Suchen",
		"ranking_classrank"=>"Klassen#",
		"ranking_allclasses" => "Gesamt",
		// Register
		"register" => "Registration",
		"register_captcha_error" => "Den Captcha, den du eingegeben hast, stimmt nicht.",
		"register_closed" => "Die Registration ist im Moment leider geschlossen.<br/>Bitte versuche es sp&auml;ter nocheinmal, da dies h&ouml;chstwahrscheinlich nur eine tempor&auml;re Ma&szlig;nahme ist.",
		"register_loggedin" => 'Du hast schon einen Account!<br/>Wenn das nicht dein Account ist logge dich bitte aus: <a href="%logouturl">Logout</a>',
		"register_passrepeat_error" => "Das Passwort und die Wiederholung stimmen nicht &uuml;berein.",
		"register_account_exists" => "Ein Account mit diesem Namen existiert bereits.",
		"register_codelen_error" => "Dein L&ouml;schcode muss 7 Zeichen lang sein.",
		"register_email_error" => "Deine Email scheint nicht richtig zu sein",
		"register_multiacc_error" => "Du hast bereits einen Account auf dieser Email",
		"register_userminlen_error" => "Dein Username muss mindestens %len Zeichen lang sein",
		"register_usermaxlen_error" => "Dein Username darf maximal %len Zeichen lang sein",
		"register_passminlen_error" => "Dein Passwort muss mindestens %len Zeichen lang sein",
		"register_passmaxlen_error" => "Dein Passwort darf maximal %len Zeichen lang sein",
		"register_secqminlen_error" => "Deine Sicherheitsfrage muss mindestens %len Zeichen lang sein",
		"register_secqmaxlen_error" => "Deine Sicherheitsfrage darf maximal %len Zeichen lang sein",
		"register_secaminlen_error" => "Deine Antwort muss mindestens %len Zeichen lang sein",
		"register_secamaxlen_error" => "Deine Antwort darf maximal %len Zeichen lang sein",
		"register_emailsubject" => "Deine Registration auf %servername",
		"register_emailbody" => "Hallo %username,\nUm deine Registrierung auf %servername zu vervollständigen, musst du nur auf diesen Link klicken:\n%url\n\nDein %servername Team",
		"register_success_emailverify" => "Deine Registration war erfolgreich!<br/>Wir haben dir eine Email geschickt um deine Email Adresse zu bestätigen<br/>Bitte klicke den Link in der Email um deinen Account zu bestätigen",
		"register_success" => "Deine Registration war erfolgreich!",
		"register_verify_error" => "Verzifizierung fehlgeschlagen!<br/>Bitte kopiere den Link wenn du Probleme hast!",
		"register_verify_success" => "Du hast deinen Account erfolgreich verifiziert!<br/>Du kannst nun mit ihm spielen!",
		"register_user"=>"Accountname",
		"register_pass"=>"Passwort",
		"register_repeat"=>"Wiederholen",
		"register_email"=>"Email",
		"register_code"=>"L&ouml;schcode",
		"register_security_question"=>"Sicherheitsfrage",
		"register_security_answer"=>"Antwort",
		"register_submit"=>"Absenden",
		// Settings
		"settings"=>"Einstellungen",
		"settings_change_password" => "Passwort &auml;ndern",
		"settings_change_password_text" => "Hier kannst du dein Passwort &auml;ndern.<br/>Du musst nur dein altes Passwort eingeben, um zu best&auml;tigen, dass dies dein Account ist.<br/>",
		"settings_change_code" => "L&ouml;schcode &auml;ndern",
		"settings_change_code_text" => "Hier kannst du deinen L&ouml;schcode &auml;ndern<br/>Du musst nur dein Passwort eingeben, um zu best&auml;tigen, dass dies dein Account ist<br/>",
		"settings_reset_safebox" => "Lagerpasswort zur&uuml;cksetzen",
		"settings_reset_safebox_text" => "Hier kannst du dein Lagerpasswort zur&uuml;cksetzen<br/>Falls du dies tust, wird es zu <b>0000000</b> ge&auml;ndert<br/>Du musst nur dein Passwort eingeben, um zu best&auml;tigen, dass dies dein Account ist<br/>",
		"settings_change_email" => "Email &auml;ndern",
		"settings_change_email_text" => "hier kannst du deine aktuelle Email &auml;ndern<br/>Du musst nur dein Passwort eingeben, um zu best&auml;tigen, dass dies dein Account ist<br/>",
		"settings_pass_error" => "Das Passwort stimmt nicht &uuml;berein!",
		"settings_pass_changed" => "Dein Passwort wurde erfolgreich ge&auml;ndert!",
		"settings_code_changed" => "Dein L&ouml;schcode wurde erfolgreich ge&auml;ndert!",
		"settings_safebox_reset" => "Dein Lagerpasswort wurde erfolgreich zur&uuml;ckgesetzt! (Es ist jetzt <b>0000000</b>)",
		"settings_emailsubject" => "Email Änderung auf %servername",
		"settings_emailbody" => "Hallo %username,\nUm deine Email Änderung auf %servername zu bestätigen, musst du auf diesen Link klicken:\n%url\nDein %servername Team",
		"settings_verifymailsent" => "Wir haben eine Email zu deiner neuen und alten Email Adresse gesendet.<br/>Bitte klicke beide Links in den Emails um deine Email zu &auml;ndern.",
		"settings_email_changed" => "Deine Email wurde erfolgreich ge&auml;ndert!",
		"settings_verify_otheremail" => "Diese Email wurde best&auml;tigt!<br/> Bitte klicke nun auf den Link in der anderen.",
		"settings_pass"=>"Passwort",
		"settings_oldpass"=>"Altes Passwort",
		"settings_repeat"=>"Wiederholen",
		"settings_code"=>"L&ouml;schcode",
		"settings_email"=>"Email",
		"settings_submit_change_pass"=>"&Auml;ndern",
		"settings_submit_change_code"=>"&Auml;ndern",
		"settings_submit_reset_safebox"=>"Zur&uuml;cksetzen",
		"settings_submit_change_email"=>"&Auml;ndern",
		// Statistics
		"statistics"=>"Statistik",
		"statistics_player"=>"Spieler",
		"statistics_playero"=>"Spieler Online",
		"statistics_items"=>"Items",
		"statistics_guilds"=>"Gilden",
		"statistics_accounts"=>"Accounts",
		// Userpanel
		"userpanel_title_loggedin" => "Mein Account",
		"userpanel_title_login" => "Login",
		"userpanel_user_placeholder"=> "Account",
		"userpanel_password_placeholder"=> "Passwort",
		"userpanel_login_failed"=> "Login fehlgeschlagen",
		"userpanel_banned"=>"Dein Account ist gebannt",
		"userpanel_hello" => "Hey %username,"
	),
	"en" => array(
		// General stuff
		"donate" => "Donate",
		"fillout" => "Please fill out all fields",
		"needlogin" => "Pleae log in",
		"youcoin" => "You have <b><span class='coins'>%coins</span></b> %coinname!",
		"coin" => "Coin",
		"coins" => "Coins",
		"online" => "online",
		"offline" => "offline",
		"warrior" => "Warrior",
		"assassin" => "Assassin",
		"sura" => "Sura",
		"shaman" => "Shaman",
		"back" => "Back",
		"next" => "Next",
		"charname" => "Name",
		"class" => "Class",
		"level" => "Level",
		"ok"=>"&radic;",
		"logout"=>"Logout",
		"login"=>"Login",
		// Time class
		"time_s" => "seconds",
		"time_S" => "second",
		"time_m" => "minutes",
		"time_M" => "minute",
		"time_h" => "hours",
		"time_H" => "hour",
		"time_D" => "day",
		"time_d" => "days",
		"time_a" => "ago",
		"time_in" => "in",
		"time_at" => "at",
		"time_af" => "a few",
		"time_ystrd" => "yesterday",
		"time_tmrw" => "tomorrow",
		"time_format" => "%value %time %ago %at",
		"time_fformat" => "%ago %value %time %at",
		"time_dformat" => "d.m.y H:i",
		// Donate_psc
		"psc_code_name" => "Code",
		"psc_donate_success" => "Your Paysafecard is valid and was successfully submited.<br/>Please wait until a staff member controlled the Paysafecard again and gives you your coins.<br/>This should <b>not</b> take longer than <b>24 Hours</b>!",
	    "psc_error_fields_blank" => "You did not fill out all fields",
		"psc_error_code" => "An error has occurred with your PIN and/or password. Please check the entry of your PIN and the password, if you have given a password to this paysafecard.",
	    "psc_error_code_pw" => "An error has occurred with your PIN and/or password. Please check the entry of your PIN and the password, if you have given a password to this paysafecard.",
	    "psc_error_captcha" => "The text entered is not the same as the one displayed.",
	    "psc_error_unknown" => "An unknown error occured. Please try again",
	    "psc_error_online" => "An unknown error occured. Please try again",
	    "psc_error_currency" => "You Paysafecards currency was not accepted.",
	    "psc_error_empty" => "The credit on your Paysafecard is too low",
	    "psc_error_try" => "This paysafecard was blocked due to too many failed attempts",
		// Itemshop
		"itemshop"=>"Itemshop",
		"itemshop_404" => "I could not find the page you were looking for",
		"itemshop_price"=>"Price",
		"itemshop_buy" => "Buy",
		"itemshop_buy_again" => "Again",
		"itemshop_itemerror" => "I could not find the item you tried to buy.",
		"itemshop_priceerror" => "You dont have enough coins to buy this",
		"itemshop_success" => "You successfully bought it!",
		// Ranking
		"ranking"=>"Ranking",
		"ranking_search_placeholder"=>"Charactername",
		"ranking_search"=>"Search",
		"ranking_classrank"=>"Class#",
		"ranking_allclasses"=>"General",
		// Register
		"register" => "Register",
		"register_captcha_error" => "The captcha you entered is wrong.",
		"register_closed" => "The registration is currently closed<br/>Please check back later cause this is probably just temporary.",
		"register_loggedin" => 'You already have an account.<br/>If this is not your account please <a href="'.$urlmap["logout"].'">Logout</a>',
		"register_passrepeat_error" => "The password and the repeated one didnt match.",
		"register_account_exists" => "An account with this name already exists",
		"register_codelen_error" => "Your code has to be 7 characters long",
		"register_email_error" => "Your email doesnt seem to be valid",
		"register_multiacc_error" => "There is already an account on this email",
		"register_userminlen_error" => "Your username has to be at least %len characters long",
		"register_usermaxlen_error" => "Your username must be under %len characters long",
		"register_passminlen_error" => "Your password has to be at least %len characters long",
		"register_passmaxlen_error" => "Your password must be under %len characters long",
		"register_emailsubject" => "Your registration on %servername",
		"register_emailbody" => "Hello %username,\nTo complete your registration on %servername you just have to click this link:\n%url\nYour %servername Team",
		"register_success_emailverify" => "Your Registration was sucessfull!<br/>An email was sent to verify your email adress is valid.<br/>Please click the link in the email to verify your account.",
		"register_success" => "Your Registration was sucessfull!",
		"register_verify_error" => "Verification failed!<br/>Please copy the link if you have trouble!",
		"register_verify_success" => "You just verified your account!<br/>You may use your account to play now",
		"register_user"=>"Account",
		"register_pass"=>"Password",
		"register_repeat"=>"Repeat",
		"register_email"=>"Email",
		"register_code"=>"Deletioncode",
		"register_security_question"=>"Security question",
		"register_security_answer"=>"Answer",
		"register_submit"=>"Submit",
		// Settings
		"settings"=>"Settings",
		"settings_change_password" => "Change Password",
		"settings_change_password_text" => "You may change your password here.<br/>You just have to enter your old one to verify you own this account.<br/>",
		"settings_change_code" => "Change Code",
		"settings_change_code_text" => "You may change your character deletion code here<br/>You just have to enter your password to verify you own this account<br/>",
		"settings_reset_safebox" => "Reset Safebox Password",
		"settings_reset_safebox_text" => "You may reset your safebox password here.<br/>It will be changed to <b>0000000</b><br/>You just have to enter your password to verify you own this account<br/>",
		"settings_change_email" => "Change email",
		"settings_change_email_text" => "You may change your current email here.<br/>You just have to enter your password to verify you own this account<br/>",
		"settings_pass_error" => "Your password didn't match!",
		"settings_pass_changed" => "Your password was successfully changed!",
		"settings_code_changed" => "Your code was successfully changed!",
		"settings_safebox_reset" => "Your safebox password was successfully reset! (It's <b>0000000</b> now)",
		"settings_emailsubject" => "Email change on %servername",
		"settings_emailbody" => "Hello %username,\nTo complete the email change on %servername you just have to click this link:\n%url\nYour %servername Team",
		"settings_verifymailsent" => "We sent an email to your new and your old email address.<br/>Please click the link in both of the emails to verify the change. Just ignore them if you don't want to anymore.",
		"settings_email_changed" => "Your email was successfully changed!",
		"settings_verify_otheremail" => "This email was verified! Please go to the other one and click the link in there to complete change your email",
		"settings_pass"=>"Password",
		"settings_oldpass"=>"Old password",
		"settings_repeat"=>"Repeat",
		"settings_code"=>"Deletioncode",
		"settings_email"=>"Email",
		"settings_submit_change_pass"=>"Change",
		"settings_submit_change_code"=>"Change",
		"settings_submit_reset_safebox"=>"Reset",
		"settings_submit_change_email"=>"Change",
		// Statistics
		"statistics"=>"Statistics",
		"statistics_player"=>"Player",
		"statistics_playero"=>"Player Online",
		"statistics_items"=>"Items",
		"statistics_guilds"=>"Guilds",
		"statistics_accounts"=>"Accounts",
		// Userpanel
		"userpanel_title_loggedin" => "Userpanel",
		"userpanel_title_login" => "Login",
		"userpanel_user_placeholder"=> "Account",
		"userpanel_password_placeholder"=> "Password",
		"userpanel_login_failed"=> "Login failed",
		"userpanel_banned"=>"You are banned",
		"userpanel_hello" => "Hey %username,"
	)
);
?>